name: Create KB
description: This description is mandatory
labels: 'kb-from-escalation'
assignees:
  - timburgan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this goodness
  - type: input
    id: url
    attributes:
      label: URL of Engineering Escalation
      placeholder: ex. https://github.com/github/c2c-actions-support
    validations:
      required: true
